const token=()=>localStorage.getItem('access_token');
const request=(path, options={})=>fetch(path,{...options,headers:{Authorization:`Bearer ${token()}`,...options.headers}}).then(async response=>{if(response.status===401){location='/login.html';throw Error('Session expired')}if(!response.ok)throw Error(`${path} -> ${response.status}`);return response.status===204?null:response.json()});
const $=id=>document.getElementById(id);let snapshot={};let interval='1h';
const fields=[['API','api'],['API Key','key'],['Equity (USDT)','equity_usdt'],['Available (USDT)','available_usdt'],['Leverage','max_leverage'],['Max Drawdown','max_drawdown_usdt'],['PnL (USDT)','pnl_usdt'],['Win Rate','win_rate'],['Profit Factor','profit_factor'],['Longs / Shorts','long_short'],['Gross Profit','gross_profit_usdt'],['Gross Loss','gross_loss_usdt'],['Expectancy','expectancy_usdt'],['Best / Worst','best_worst'],['Win Streak','streak'],['Unrealized PnL','unrealized_pnl_usdt'],['Fill Count','fill_count'],['Position Size','position_size'],['Wallet (USDT)','equity_usdt'],['Available','available_usdt'],['Funding Rate','funding_rate'],['Open Mismatches','open_mismatches']];
function number(value, digits=2){return Number(value||0).toLocaleString(undefined,{maximumFractionDigits:digits})}
function display(key, stats){const value=stats[key];if(key==='api')return snapshot.accounts.length?'ESTABLISHED':'NOT CONFIGURED';if(key==='key')return snapshot.accounts.length?'•••• CONFIGURED':'—';if(key==='max_leverage')return `${number(value,1)}x`;if(key==='max_drawdown_usdt')return `${number(value)} USDT`;if(key==='win_rate')return `${number(value*100)}%`;if(key==='profit_factor'||key==='funding_rate')return value==null?'—':number(value,4);if(key==='long_short')return `${stats.longs||0} / ${stats.shorts||0}`;if(key==='best_worst')return `${number(stats.best_trade_usdt)} / ${number(stats.worst_trade_usdt)}`;if(key==='streak')return `${stats.consecutive_wins||0} / ${stats.consecutive_losses||0}`;return number(value)}
function render(){const stats=snapshot.stats||{};$('cards').innerHTML=fields.map(([label,key])=>`<article class="card"><div class="label">${label}</div><div class="value ${Number(stats[key])<0?'red':''}">${display(key,stats)}</div></article>`).join('');const account=snapshot.accounts?.[0];$('account').textContent=account?`ACCOUNT ${account.environment.toUpperCase()}`:'ACCOUNT —';$('bot').textContent='RUNNING';$('bot').className='badge green';$('kill').textContent=snapshot.kill_switch?'KILL ACTIVE':'KILL OFF';$('kill').className=`badge ${snapshot.kill_switch?'red':'green'}`;const assets=[...new Set(['BTCUSDT',...(snapshot.assets||[])])];$('asset').innerHTML=assets.map(item=>`<option>${item}</option>`).join('');$('tradeRows').innerHTML=(snapshot.trades||[]).map(trade=>`<tr><td>${String(trade.entry_time||'').replace('T',' ').slice(0,19)}</td><td>${trade.asset||'—'}</td><td class="${String(trade.side||'').toLowerCase()}">${trade.side||'—'}</td><td>${number(trade.quantity,5)}</td><td>${number(trade.entry_price,4)}</td><td>${trade.exit_price==null?'—':number(trade.exit_price,4)}</td><td class="${Number(trade.pnl)<0?'loss':'win'}">${trade.pnl==null?'—':number(trade.pnl)}</td><td>${trade.outcome||'open'}</td></tr>`).join('')||'<tr><td colspan="8">No trades</td></tr>';$('updated').textContent=new Date().toLocaleTimeString()}
async function chart(){const candles=await request(`/api/candles?asset=${encodeURIComponent($('asset').value)}&limit=200`);const last=candles.at(-1);if(last)$('ohlc').textContent=`O ${number(last.open)}　H ${number(last.high)}　L ${number(last.low)}　C ${number(last.close)}　V ${number(last.volume,0)}`;Plotly.react('chartPlot',[{type:'candlestick',x:candles.map(row=>row.timestamp),open:candles.map(row=>row.open),high:candles.map(row=>row.high),low:candles.map(row=>row.low),close:candles.map(row=>row.close)}],{paper_bgcolor:'#111',plot_bgcolor:'#111',font:{color:'#ccc'},xaxis:{rangeslider:{visible:false}},margin:{l:50,r:15,t:25,b:35}},{responsive:true,displayModeBar:false})}
async function load(){try{const [dashboard,status]=await Promise.all([request('/api/dashboard'),request('/api/status')]);snapshot={...dashboard,...status};render();if(document.querySelector('[data-panel="chart"].active'))await chart();$('error').textContent=''}catch(error){$('error').textContent=error.message}}
document.querySelectorAll('.tab').forEach(button=>button.onclick=async()=>{document.querySelectorAll('.tab,.panel').forEach(item=>item.classList.remove('active'));button.classList.add('active');$(`${button.dataset.panel}`).classList.add('active');if(button.dataset.panel==='chart')await chart()});document.querySelectorAll('[data-interval]').forEach(button=>button.onclick=()=>{interval=button.dataset.interval;document.querySelectorAll('[data-interval]').forEach(item=>item.classList.toggle('active',item===button));chart()});$('asset').onchange=chart;$('refresh').onclick=load;$('logout').onclick=()=>{localStorage.clear();location='/login.html'};$('killButton').onclick=async()=>{const state=await request('/api/kill');await request(state.active?'/api/kill/reset':'/api/kill/activate',{method:'POST'});load()};load();setInterval(load,15000);
